---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: null
sections:
  - type: directory
    path: content
    label: Pages
    create: all
  - type: directory
    path: content/posts
    label: Posts
    create: all
  - type: document
    label: Config
    path: config.yaml
    templates:
      - config
upload_dir: static/uploads
public_path: /uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
version: '0.47'
