---
label: Config
hide_body: true
is_partial: false
fields:
  - type: text
    name: title
    label: Title
    description: Site title
    config:
      required: true
  - type: field_group
    name: params
    label: Params
    description: Site parameters
    fields:
      - type: field_group
        name: footer
        label: Footer
        description: Footer configuration
        fields:
          - type: field_group_list
            name: social_links
            label: Social Links
            description: Links to social pages
            config:
              labelField: title
            fields:
              - type: text
                name: title
                label: Title
              - type: text
                name: icon
                label: Icon
                description: Font Awesome Icon
              - type: text
                name: link_url
                label: Link URL
